# Khipus.ai
## Fundamentals of Data Science
### Python (NumPy)
<span>© Copyright Notice 2025, Khipus.ai - All Rights Reserved.</span>

### What is NumPy and its value to data science
NumPy is a powerful Python library for numerical computing. It provides support for:
- Multi-dimensional arrays and matrices
- A collection of mathematical functions to operate on arrays

In data science, NumPy is extremely useful because it:
- Efficient storage and manipulation of numerical data
- Foundation for many other libraries like Pandas and scikit-learn
- Performance improvements over standard Python data structures like lists

# Package installation

To install the NumPy package from a Jupyter Notebook, you can use the following command within a code cell:

In [1]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeable
   ---------------------------------------- 0.0/12.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.4 MB ? eta -:--:--
    --------------------------------------- 0.3/12.4 MB ? eta -:--:--
   - -------------------------------------- 0.5/12.4 MB 1.6 MB/s eta 0:00:08
   -- ------------------------------------- 0.8/12.4 MB 1.3 MB/s eta 0:00:09
   --- ------------------------------------ 1.0/12.4 MB 1.2 MB/s eta 0:00:10
   ---- ----------------------------------- 1.3/12.4 MB 1.2 MB/s eta 0:00:10
   ----- ---------------------------------- 1.6/12.4 MB 1.2 MB/s eta 0:00:10
   ----- ---------------------------------- 1.8/12.4 MB 1.3 MB/s eta 0:00:09
   ------ --------------------------------- 2.1/12.4 MB 1.3 MB/s eta 0:00:09
   -------- ------------------------------- 2.6/12.4 MB 1.4 MB/s eta 0:00:08
   --------- ------------------------------ 2.9/12.4 MB 1.4 MB/s eta 0:00:07
   ---------- -----

# Importing NumPy

In [2]:
# Importing NumPy
import numpy as np

### Array Creation
NumPy provides multiple ways to create arrays, such as:
- `np.array()`: Convert Python lists or tuples into arrays
- `np.zeros()`: Create an array filled with zeros
- `np.ones()`: Create an array filled with ones
- `np.arange()`: Create arrays with a range of values

In [3]:
# Example: Creating a simple NumPy array from a Python list
example_array = np.array([1, 2, 3, 4, 5])
print("Example Array:", example_array)

Example Array: [1 2 3 4 5]


In [4]:
# Example: Creating arrays using built-in NumPy functions
zeros_array = np.zeros((2, 3))
ones_array = np.ones((3, 3))
range_array = np.arange(0, 10, 2)

print("Zeros Array:")
print(zeros_array)
print("Ones Array:")
print(ones_array)
print("Range Array:", range_array)

Zeros Array:
[[0. 0. 0.]
 [0. 0. 0.]]
Ones Array:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Range Array: [0 2 4 6 8]


### Indexing and Slicing
Indexing and slicing in NumPy is used to access and modify array elements.
- Use square brackets `[]` for accessing array elements
- Slice arrays using the colon `:` operator

In [5]:
# Example: Indexing and Slicing
array_example = np.array([10, 20, 30, 40, 50])
print("Element at index 2:", array_example[2])
print("Slice from index 1 to 3:", array_example[1:4])



Element at index 2: 30
Slice from index 1 to 3: [20 30 40]


In [6]:
# Example: Multi-dimensional arrays
multi_dim_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Element at row 2, col 3:", multi_dim_array[1, 2])
print("First row:", multi_dim_array[0, :])

Element at row 2, col 3: 6
First row: [1 2 3]


### Reshaping Arrays
Reshaping changes the shape of an existing array without altering its data.
- Use `.reshape()` to modify array dimensions

In [7]:
# Example: Reshaping Arrays one-dimensional to multi-dimensional
original_array = np.arange(1, 13)

# Reshaping in 3 rows and 4 cols array
reshaped_array = original_array.reshape(3, 4)
print("Original Array:", original_array)
print("Reshaped Array:")
print(reshaped_array)

Original Array: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Reshaped Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


# Arrays operations
This is an example of an array operation. Specifically, it is an element-wise multiplication of two NumPy arrays. Each element in one array is multiplied by the corresponding element in the other array.


Explanation:

np.arange(5) creates an array x with values [0, 1, 2, 3, 4].

np.arange(1, 6) creates an array y with values [1, 2, 3, 4, 5].


x * y performs element-wise multiplication of the two arrays:
0 * 1 = 0

1 * 2 = 2

2 * 3 = 6

3 * 4 = 12

4 * 5 = 20

The result is an array [0, 2, 6, 12, 20].


In [8]:
# Create an array with values [0, 1, 2, 3, 4]
x = np.arange(5)

# Create an array with values [1, 2, 3, 4, 5]
y = np.arange(1, 6)

# Perform element-wise multiplication of arrays x and y
result = x * y

print(result)

[ 0  2  6 12 20]


### Universal Functions (Ufuncs)
Ufuncs (Universal Functions) are functions that operate element-wise on arrays.
- Examples: `np.add()`, `np.multiply()`, `np.sqrt()`, `np.exp()`

In [9]:
# Example: Using Ufuncs
array_ufunc = np.array([1, 4, 9, 16])
sqrt_array = np.sqrt(array_ufunc)
add_array = np.add(array_ufunc, 10)

print("Original Array:", array_ufunc)
print("Square Root Array:", sqrt_array)
print("Array after adding 10:", add_array)

Original Array: [ 1  4  9 16]
Square Root Array: [1. 2. 3. 4.]
Array after adding 10: [11 14 19 26]
